# fly.toml file generated for old-pond-2370 on 2021-07-16T11:09:05-05:00

app = "old-pond-2370"

kill_signal = "SIGINT"
kill_timeout = 5

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = false

[metrics]
  path = "/metrics"
  port = 2379

[[mounts]]
  destination = "/etcd_data"
  source = "etcd_data"

[[services]]
  internal_port = 2379

  [services.concurrency]

  [[services.ports]]
    handlers = []
    port = 10000

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
