# fly.toml file generated for still-star-2028 on 2021-07-21T23:13:53-05:00

app = "still-star-2028"

kill_signal = "SIGINT"
kill_timeout = 5

[checks]

  [checks.role]
    args = ["vm"]
    command = "flycheck"
    interval = 60000
    restart_limit = 0
    timeout = 10000
    type = "script"

[env]
  TARGET_CLUSTER_SIZE = 3 

[experimental]
  allowed_public_ports = []
  auto_rollback = false

[[mounts]]
  destination = "/etcd_data"
  source = "etcd_data"

[[services]]
  internal_port = 2379

  [services.concurrency]

  [[services.ports]]
    handlers = []
    port = 10000

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
