# fly.toml file generated for lively-lake-2200 on 2021-07-27T17:28:38-05:00

app = "lively-lake-2200"

kill_signal = "SIGINT"
kill_timeout = 5

[mounts]
  source="etcd_data"
  destination="/etcd_data"

[checks.etcd]
type         = "script"
interval     = 30000
timeout      = 10000
grace_period = "10s"
command      = "flycheck"
args         = [ "etcd" ]
restart_limit = 0

[checks.vm]
type     = "script"
interval = 30000
timeout  = 10000
command  = "flycheck"
args     = [ "vm" ]
restart_limit = 0

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 2379
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

