# fly.toml file generated for lively-lake-2200 on 2021-07-27T17:28:38-05:00

app = "fly-etcd-na"

kill_signal = "SIGTERM"
kill_timeout = 30

[metrics]
  port = 2379
  path = "/metrics"

[mounts]
  source="etcd_data"
  destination="/etcd_data"

[checks.etcd]
  type         = "script"
  interval     = 30000
  timeout      = 10000
  grace_period = "10s"
  command      = "flycheck"
  args         = [ "etcd" ]
  restart_limit = 0

[checks.vm]
  type     = "script"
  interval = 30000
  timeout  = 10000
  command  = "flycheck"
  args     = [ "vm" ]
  restart_limit = 0

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 2379
  protocol = "tcp"
  script_checks = []

  [[services.ports]]
    handlers = []
    port = 10000

  [[services.ports]]
    handlers  = ["tls"]
    port = 443
    tls_options = { alpn = ["h2"] }

  [services.concurrency]
    hard_limit = 1000
    soft_limit = 300
    type = "connections"


 [[services.tcp_checks]]
    grace_period = "40"
    interval = "10s"
    restart_limit = 0
    timeout = "2s"
