
app = 'shaun-etcd-test-2'
primary_region = 'ord'
kill_signal = 'SIGTERM'
kill_timeout = '30s'

[experimental]
  auto_rollback = true

[build]

[[mounts]]
  source = 'etcd_data'
  destination = '/data'

[http_service]
  internal_port = 2379
  force_https = true
  auto_start_machines = true
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 2379
  auto_start_machines = false

  [[services.ports]]
    port = 10000

  [[services.ports]]
    port = 443
    handlers = ['tls']

    [services.ports.tls_options]
      alpn = ['h2']

  [services.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 300

[checks]
  [checks.etcd]
    port = 5500
    type = 'http'
    interval = '15s'
    timeout = '10s'
    grace_period = '30s'
    method = 'get'
    path = '/flycheck/etcd'

  [checks.vm]
    port = 5500
    type = 'http'
    interval = '1m0s'
    timeout = '10s'
    grace_period = '1s'
    method = 'get'
    path = '/flycheck/vm'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[metrics]]
  port = 2112
  path = '/metrics'
  https = false
