# fly.toml app configuration file generated for shaun-etcd-test on 2024-10-14T16:06:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shaun-etcd-test'
kill_signal = 'SIGTERM'
kill_timeout = '30s'

[experimental]
  auto_rollback = true

[[mounts]]
  source = 'etcd_data'
  destination = '/data'

[checks]
  [checks.etcd]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/flycheck/etcd"
    port = 5500
    timeout = "10s"
    type = "http"

  [checks.vm]
    grace_period = "1s"
    interval = "1m"
    method = "get"
    path = "/flycheck/vm"
    port = 5500
    timeout = "10s"
    type = "http"

[[services]]
  protocol = 'tcp'
  internal_port = 2379
  auto_start_machines = false

  [[services.ports]]
    port = 10000

  [[services.ports]]
    port = 443
    handlers = ['tls']

    [services.ports.tls_options]
      alpn = ['h2']

  [services.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 300

[[metrics]]
  port = 2379
  path = '/metrics'
