name: Release

on:
  create:

jobs:
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: "Fetch latest tag"
        id: get-latest-tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      -
        name: Build and push Etcd
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          build-args: |
            ETCD_VERSION=3.5.16
            FLY_VERSION=${{ steps.get-latest-tag.outputs.tag }}
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            flyio/fly-etcd:3
            flyio/fly-etcd:3.5
            flyio/fly-etcd:3.5.16
      -
        name: Etcd Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

